version: '4.15'

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-kotfi
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: kotfi
        ports:
            - 27017:27017
        volumes:
            - C:\Documents\Docker\mongodb\mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro